In [21]:
import pandas as pd
import numpy as np
data={
    "Name":["Rohit","Santosh","Ranvir"],
    "Age":[22, 25,23],
    "marks":[25,30,35],  
    "city":['pune','mumbai','delhi']
    
}
df =pd.DataFrame(data)
print("Student Records\n\n", df)

Student Records

       Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi

# I want to drop Column

In [22]:
# I want to drop marks Column
df.drop("Name",axis=1)

   Age  marks    city
0   22     25    pune
1   25     30  mumbai
2   23     35   delhi

In [23]:
df.drop('Name',axis=0,errors = 'ignore')

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi

In [24]:
df.drop(columns=['Name'])

   Age  marks    city
0   22     25    pune
1   25     30  mumbai
2   23     35   delhi

In [25]:
df.drop(columns=df.columns[2])

      Name  Age    city
0    Rohit   22    pune
1  Santosh   25  mumbai
2   Ranvir   23   delhi

# Inplace
- When we some operation the output will not reflect in origional
- at the time check the  **inplace** operator
- if the **inplace =False** the result will not over write
- make sure inplace=True should be provide , inorder overwrite the output

# How to  add row
- loc and iloc operation

In [26]:
df.loc[2]

Name     Ranvir
Age          23
marks        35
city      delhi
Name: 2, dtype: object

In [27]:
d1={'Name':'Pratham','Age':22,'marks':95,'city':'pune'}

In [28]:
df.loc[3]=d1

In [29]:
df

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune

# How to add row at the end

In [30]:
df.loc[len(df)]=d1={'Name':'Pratham','Age':22,'marks':95,'city':'pune'}

# How to read a last row when we have large dataset

In [31]:
df.iloc[len(df)-1]

Name     Pratham
Age           22
marks         95
city        pune
Name: 4, dtype: object

In [32]:
df

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune
4  Pratham   22     95    pune

In [33]:
df.drop_duplicates()

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune

In [34]:
data={
    "Name":["Rohit","Santosh","Ranvir"],
    "Age":[22, 25,23],
    "marks":[25,30,35],  
    "city":['pune','mumbai','delhi']
    
}
df1=pd.DataFrame(data)

In [35]:
df1

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi

In [36]:
data={
    "Name":["Rohit","Santosh","Ranvir"],
    "Age":[22, 25,23],
    "marks":[25,30,35],  
    "city":['pune','mumbai','delhi']
    
}
df2=pd.DataFrame(df2)

NameError: name 'df2' is not defined

NameError: name 'df2' is not defined

In [38]:
df3=pd.concat([df1,df2],ignore_index=True)

NameError: name 'df2' is not defined

In [ ]:
df3

# How to rename the Column

In [ ]:
df.rename(columns={'marks':'Percenteges'})

In [ ]:
d={'marks':'percentages'}
df.rename(d,axis=1)
df.rename(d)
df.rename(d,axis=0)
df.rename(index=d)
df.rename(columns=d)
df.drop_duplicates()