In [106]:
import pandas as pd
import numpy as np
data={
    "Name":["Rohit","Santosh","Ranvir"],
    "Age":[22, 25,23],
    "marks":[25,30,35],  
    "city":['pune','mumbai','delhi']
    
}
df =pd.DataFrame(data)
print("Student Records\n\n", df)

Student Records

       Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi

# I want to drop Column

In [107]:
# I want to drop marks Column
df.drop("Name",axis=1)

   Age  marks    city
0   22     25    pune
1   25     30  mumbai
2   23     35   delhi

In [108]:
df.drop('Name',axis=0)

KeyError: "['Name'] not found in axis"

In [ ]:
df.drop('Name',axis=0,errors = 'ignore')

In [ ]:
df.drop(columns=['Name'])

In [ ]:
df.drop(columns=2)

# Inplace
- When we some operation the output will not reflect in origional
- at the time check the  **inplace** operator
- if the **inplace =False** the result will not over write
- make sure inplace=True should be provide , inorder overwrite the output

# How to  add row
- loc and iloc operation

In [ ]:
df.loc[2]

In [109]:
d1={'Name':'Pratham','Age':22,'marks':95,'city':'pune'}

In [110]:
df.loc[3]=d1

In [111]:
df

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune

# How to add row at the end

In [112]:
df.loc[len(df)]=d1={'Name':'Pratham','Age':22,'marks':95,'city':'pune'}

# How to read a last row when we have large dataset

In [113]:
df.iloc[len(df)-1]

Name     Pratham
Age           22
marks         95
city        pune
Name: 4, dtype: object

In [114]:
df

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune
4  Pratham   22     95    pune

In [115]:
df.drop_duplicates()

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune

In [116]:
data={
    "Name":["Rohit","Santosh","Ranvir"],
    "Age":[22, 25,23],
    "marks":[25,30,35],  
    "city":['pune','mumbai','delhi']
    
}
df1=pd.DataFrame(data)

In [117]:
df1

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi

In [118]:
data={
    "Name":["Rohit","Santosh","Ranvir"],
    "Age":[22, 25,23],
    "marks":[25,30,35],  
    "city":['pune','mumbai','delhi']
    
}
df2=pd.DataFrame(df2)

In [119]:
df2

   surname  values  Random    city
0    Rohit      22      25    pune
1  Santosh      25      30  mumbai
2   Ranvir      23      35   delhi

In [120]:
df3=pd.concat([df1,df2],ignore_index=True)

In [121]:
df3

      Name   Age  marks    city  surname  values  Random
0    Rohit  22.0   25.0    pune      NaN     NaN     NaN
1  Santosh  25.0   30.0  mumbai      NaN     NaN     NaN
2   Ranvir  23.0   35.0   delhi      NaN     NaN     NaN
3      NaN   NaN    NaN    pune    Rohit    22.0    25.0
4      NaN   NaN    NaN  mumbai  Santosh    25.0    30.0
5      NaN   NaN    NaN   delhi   Ranvir    23.0    35.0

# How to rename the Column

In [128]:
df.rename(columns={'marks':'Percenteges'})

      Name  Age  Percenteges    city
0    Rohit   22           25    pune
1  Santosh   25           30  mumbai
2   Ranvir   23           35   delhi
3  Pratham   22           95    pune
4  Pratham   22           95    pune

In [136]:
d={'marks':'percentages'}
df.rename(d,axis=1)
df.rename(d)
df.rename(d,axis=0)
df.rename(index=d)
df.rename(columns=d)
df.drop_duplicates()

      Name  Age  marks    city
0    Rohit   22     25    pune
1  Santosh   25     30  mumbai
2   Ranvir   23     35   delhi
3  Pratham   22     95    pune