In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r"D:\Data-Science\ML\CampusX\cars.csv")

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     120000  Petrol   First Owner         450000
1    Skoda     140000  Diesel  Second Owner         370000
2    Honda     127000  Diesel   Third Owner         158000
3  Hyundai     120000  Petrol   First Owner         225000
4   Maruti      85000  Diesel   First Owner         130000

In [5]:
df['owner'].value_counts()

owner
First Owner     53
Second Owner    28
Third Owner     21
Name: count, dtype: int64

# 1. One hot encoding pandas

In [10]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_Petrol,owner_First Owner,owner_Second Owner,owner_Third Owner
0,Maruti,120000,450000,0,0,1,1,0,0
1,Skoda,140000,370000,0,1,0,0,1,0
2,Honda,127000,158000,0,1,0,0,0,1
3,Hyundai,120000,225000,0,0,1,1,0,0
4,Maruti,85000,130000,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
97,Maruti,84500,325000,1,0,0,1,0,0
98,Ford,155000,200000,0,1,0,0,0,1
99,Toyota,115000,680000,0,0,1,1,0,0
100,Honda,133000,345000,0,1,0,0,1,0
101,Hyundai,93000,465000,0,0,1,1,0,0

,brand,km_driven,selling_price,fuel_Diesel,fuel_Petrol,owner_Second Owner,owner_Third Owner
0,Maruti,120000,450000,0,1,0,0
1,Skoda,140000,370000,1,0,1,0
2,Honda,127000,158000,1,0,0,1
3,Hyundai,120000,225000,0,1,0,0
4,Maruti,85000,130000,1,0,0,0
...,...,...,...,...,...,...,...
97,Maruti,84500,325000,0,0,0,0
98,Ford,155000,200000,1,0,0,1
99,Toyota,115000,680000,0,1,0,0
100,Honda,133000,345000,1,0,1,0
101,Hyundai,93000,465000,0,1,0,0

# 2. k-1 OneHotEncoding

In [12]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True,dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_Petrol,owner_Second Owner,owner_Third Owner
0,Maruti,120000,450000,0,1,0,0
1,Skoda,140000,370000,1,0,1,0
2,Honda,127000,158000,1,0,0,1
3,Hyundai,120000,225000,0,1,0,0
4,Maruti,85000,130000,1,0,0,0
...,...,...,...,...,...,...,...
97,Maruti,84500,325000,0,0,0,0
98,Ford,155000,200000,1,0,0,1
99,Toyota,115000,680000,0,1,0,0
100,Honda,133000,345000,1,0,1,0
101,Hyundai,93000,465000,0,1,0,0

# 3. One Hot Encoding using sklearn

In [13]:
from sklearn.model_selection import train_test_split

In [15]:
X=df.iloc[:,:-1]

In [18]:
y=df.iloc[:,-1]

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
ohe=OneHotEncoder()

In [32]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [34]:
X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray

In [39]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(81, 8)

# 4. One Hot Encodeing with top categories

In [56]:
counts=df['brand'].value_counts()

brand
Maruti      18
Hyundai     18
Honda       17
Toyota      16
Skoda        9
Ford         9
Tata         8
Mahindra     7
Name: count, dtype: int64

In [59]:
df['brand'].nunique()
threshold=10
repl =counts[counts<=threshold].index

In [60]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int)

     Honda  Hyundai  Maruti  Toyota  uncommon
0        0        0       1       0         0
1        0        0       0       0         1
2        1        0       0       0         0
3        0        1       0       0         0
4        0        0       1       0         0
..     ...      ...     ...     ...       ...
97       0        0       1       0         0
98       0        0       0       0         1
99       0        0       0       1         0
100      1        0       0       0         0
101      0        1       0       0         0

[102 rows x 5 columns]