In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
d={
    'Names':['Ramesh','Suresh','Satish','Mahesh'],
    'Age':[20,22,24,26],
    'City':['Hyd','Blr','Pune','Mumbai']
}
df=pd.DataFrame(d)

In [4]:
df.head()

    Names  Age    City
0  Ramesh   20     Hyd
1  Suresh   22     Blr
2  Satish   24    Pune
3  Mahesh   26  Mumbai

In [5]:
d1={
    'Names':['Ramesh','Suresh',None,'Mahesh'],
    'Age':[20,22,24,None],
    'City':[None,'Blr','Pune','Mumbai']
}
df1=pd.DataFrame(d1)
df1

    Names   Age    City
0  Ramesh  20.0    None
1  Suresh  22.0     Blr
2    None  24.0    Pune
3  Mahesh   NaN  Mumbai

- Even thought we provided None thw numerical by default Nam
- Categorical columns takes a None

In [6]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [7]:
df1.isnull()

   Names    Age   City
0  False  False   True
1  False  False  False
2   True  False  False
3  False   True  False

In [8]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [9]:
df1.to_csv('df1.csv',index=False)

In [13]:
d2={
    'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
    'Age':[20,22,24,np.nan],
    'City':[np.nan,'Blr','Pune','Mumbai']
}
df2=pd.DataFrame(d2)
df2

    Names   Age    City
0  Ramesh  20.0     NaN
1  Suresh  22.0     Blr
2     NaN  24.0    Pune
3  Mahesh   NaN  Mumbai

In [14]:
df2.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [15]:
df.dtypes

Names    object
Age       int64
City     object
dtype: object

# None vs np.nan

In [16]:
arr1=np.array([100,200,None])
arr2=np.array([100,200,np.nan])

In [17]:
sum(arr1)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [25]:
print(sum(arr2))     # 100+200+nan
print(np.nansum(arr2)) # 100+200

nan
300.0

In [26]:
np.nansum(arr2).astype(int)

300

In [30]:
arr3=np.array([10,20,'30',40])
arr3

array(['10', '20', '30', '40'], dtype='<U11')

In [34]:
arr4=np.array([10,20,'30+++',40])
arr4

array(['10', '20', '30+++', '40'], dtype='<U11')

In [35]:
arr5=np.array([10,20,'Thirty',40])
arr5

array(['10', '20', 'Thirty', '40'], dtype='<U11')

In [38]:
arr6=np.array([10,20,'30',40])
arr6.astype(int)

array([10, 20, 30, 40])

# fill with random value*

In [41]:
d2={
    'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
    'Age':[20,22,24,np.nan],
    'City':[np.nan,'Blr','Pune','Mumbai']
}
df2=pd.DataFrame(d2)
df2.fillna(0)

    Names   Age    City
0  Ramesh  20.0       0
1  Suresh  22.0     Blr
2       0  24.0    Pune
3  Mahesh   0.0  Mumbai

In [49]:
d2={
    'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
    'Age':[20,22,24,np.nan],
    'City':[np.nan,'Blr','Pune','Mumbai']
}
df2=pd.DataFrame(d2)
df2['Names'].fillna(df2['Names'].mode())
df2['Age'].fillna(df2['Age'].mean().astype(int))

0    20.0
1    22.0
2    24.0
3    22.0
Name: Age, dtype: float64

In [54]:
d2={
    'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
    'Age':[20,22,24,np.nan],
    'City':[np.nan,'Blr','Pune','Mumbai']
}
df2=pd.DataFrame(d2)
df2['Names'].fillna(df2['Names'].mode())
df2['Age'].fillna(df2['Age'].mean().astype(int))

0    20.0
1    22.0
2    24.0
3    22.0
Name: Age, dtype: float64

In [57]:
n=len(df2)

In [60]:
df2.loc[n]=['Ashish',50,'yavatamal']

In [63]:
mean_value=df2['Age'].mean()
df2['Age'].fillna(mean_value)

0    20.0
1    22.0
2    24.0
3    29.0
4    50.0
Name: Age, dtype: float64

# Methods
- method argument is there
   - bfill
   - ffill
   - pad
   - backfill
- do not provide any value just apply methos='pad'

In [66]:
df2.bfill()

    Names   Age       City
0  Ramesh  20.0        Blr
1  Suresh  22.0        Blr
2  Mahesh  24.0       Pune
3  Mahesh  50.0     Mumbai
4  Ashish  50.0  yavatamal

In [67]:
d2={
    'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
    'Age':[20,22,24,np.nan],
    'City':[np.nan,'Blr','Pune','Mumbai']
}
df2=pd.DataFrame(d2)
df2

    Names   Age    City
0  Ramesh  20.0     NaN
1  Suresh  22.0     Blr
2     NaN  24.0    Pune
3  Mahesh   NaN  Mumbai

In [76]:
df2['Age'].bfill()

0    20.0
1    22.0
2    24.0
3     NaN
Name: Age, dtype: float64

In [71]:
df2['Names'].ffill()

0    Ramesh
1    Suresh
2    Suresh
3    Mahesh
Name: Names, dtype: object

In [74]:
df2['Age'].pad()

C:\Users\rohit\AppData\Local\Temp\ipykernel_3184\385946167.py:1: FutureWarning: DataFrame.pad/Series.pad is deprecated. Use DataFrame.ffill/Series.ffill instead
  df2['Age'].pad()

0    20.0
1    22.0
2    24.0
3    24.0
Name: Age, dtype: float64

In [75]:
df['Age'].backfill()

C:\Users\rohit\AppData\Local\Temp\ipykernel_3184\532934702.py:1: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df['Age'].backfill()

0    20
1    22
2    24
3    26
Name: Age, dtype: int64

In [98]:
# d={
#     'dept':['Eng','Eng','Civil','Civil','Eng'],
#     'Sal':[70,80,50,70,np.nan]
# }

In [105]:
df=pd.DataFrame(d)

In [106]:
# con=df['dept']='Eng'
d={
    'dept':['Eng','Eng','Civil','Civil','Eng'],
    'Sal':[70,80,50,70,np.nan]
}
df.groupby(df['dept'])['Sal'].mean()

dept
Civil    60.0
Eng      75.0
Name: Sal, dtype: float64

##