# Step 1 :-  Import the packages

In [4]:
import pandas as pd    # it  is used to perform database operations
import numpy as np     # it  is used to perform numerical operations
import matplotlib.pyplot as plt  #it  is used to  draw Diagram
import seaborn as sns

 # Create a data frame using list

In [6]:
l=['ramesh','suresh','satish']
df=pd.DataFrame(l)

In [7]:
df

        0
0  ramesh
1  suresh
2  satish

In [ ]:
pd.DataFrame(data,index,columns)
data => Array, List
index => Array, List
columns => Array, List

#  First way

In [14]:
l=['ramesh','suresh','satish']
df=pd.DataFrame(l)
df['age']=[10,20,30]

In [15]:
df

        0  age
0  ramesh   10
1  suresh   20
2  satish   30

# Second Way

In [31]:
l=['ramesh','suresh','satish']
age=[10,20,30]
data=zip(l,age)
df=pd.DataFrame(data,columns=['l','age'],index=['a','b','c'])
df

        l  age
a  ramesh   10
b  suresh   20
c  satish   30

In [35]:
l=['ramesh','suresh','satish']
age=[10,20,30]
data=zip(l,age)
df=pd.DataFrame(data,['a','b','c'],columns=['Names','age'])
df

    Names  age
a  ramesh   10
b  suresh   20
c  satish   30

# Step-1:add the column name

In [38]:
l=['ramesh','suresh','satish']
age=[10,20,30]
data=zip(l,age)
df=pd.DataFrame(data,['a','b','c'],columns=['Names','age'])
df

    Names  age
a  ramesh   10
b  suresh   20
c  satish   30

In [47]:
l=['ramesh','suresh','satish']
age=[10,20,30]
data=zip(l,age)
cols=['Names','age']
df=pd.DataFrame(data,['a','b','c'],columns=cols)
df

    Names  age
a  ramesh   10
b  suresh   20
c  satish   30

In [48]:
l=['ramesh','suresh','satish']
age=[10,20,30]
city=['pune','mumbai','hydrabad']
data=zip(l,age,city)
cols=['Names','age','city']
df=pd.DataFrame(data,['a','b','c'],columns=cols)
df

    Names  age      city
a  ramesh   10      pune
b  suresh   20    mumbai
c  satish   30  hydrabad

#  Step No :- 7
**alredy dataframe availabe we need to add extra columns**

In [50]:
l=['ramesh','suresh','satish']
age=[10,20,30]
city=['pune','mumbai','hydrabad']
data=zip(l,age,city)
cols=['Names','age','city']
df=pd.DataFrame(data,['a','b','c'],columns=cols)
df['marks']=[10,20,30]

In [51]:
df

    Names  age      city  marks
a  ramesh   10      pune     10
b  suresh   20    mumbai     20
c  satish   30  hydrabad     30

- for already existed dataframe the above method
- if column not availabe it will create  a new column
- if column already availabe it will update values
- make sure while crreating or updating values the values should be equal to number of rows

# Create a empty dataframe and update the values

In [57]:
# l=['ramesh','suresh','satish']
# age=[10,20,30]
# city=['pune','mumbai','hydrabad']
# data=zip(l,age,city)
cols=['Names','age','city','marks']
df=pd.DataFrame(data,['a','b','c'],columns=cols)
# df['marks']=[10,20,30]

In [59]:
df['Names']=['ramesh','suresh','satish']
df['age']=[10,20,30]
df['city']=['pune','mumbai','hydrabad']
df['marks']=[10,20,30]

In [60]:
df

    Names  age      city  marks
a  ramesh   10      pune     10
b  suresh   20    mumbai     20
c  satish   30  hydrabad     30

In [74]:
data={
    'Names':['ramesh','suresh','satish'],
    'age':[10,20,30],
    'city':['pune',None,'hydrabad'],
    'marks':[10,20,30]
}
df=pd.DataFrame(data,index=['a','b','c'])

In [77]:
df.isnull().sum()

Names    0
age      0
city     0
marks    0
dtype: int64

In [76]:
df['city'].fillna('hydrabad',inplace=True)

C:\Users\rohit\AppData\Local\Temp\ipykernel_19064\3655656848.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('hydrabad',inplace=True)

In [78]:
data={
    'Names':'ramesh',
    'age':10,
    'city':'pune',
    'marks':10
}
df=pd.DataFrame(data,index=['a','b','c'])

In [79]:
df

    Names  age  city  marks
a  ramesh   10  pune     10
b  ramesh   10  pune     10
c  ramesh   10  pune     10

In [80]:
data={
    'Names':'ramesh',
    'age':10,
    'city':'pune',
    'marks':10
}
df=pd.DataFrame(data)

ValueError: If using all scalar values, you must pass an index

In [81]:
data={
    'Names':'ramesh',
    'age':10,
    'city':'pune',
    'marks':10
}
df=pd.DataFrame(data,index=['a'])

In [82]:
df

    Names  age  city  marks
a  ramesh   10  pune     10

# Save the DataFrame

- On what name we want to save   **file Name**
- At what location we want to save **Directory**
- Same python location then no need to mention
- If different from python location then need to provide
- Extension of the file
    - .CSV (comma seperated file)
    - .xlsx (Excel sheet)

In [88]:
df.to_csv('data.csv',index=False)

# Step-11: Read the Dataframe

In [89]:
pd.read_csv('data.csv')

    Names  age  city  marks
0  ramesh   10  pune     10